### ISSUE TITLE
Gender feature applied too widely

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-ParTUT#2]
Several hundred non-pronouns receive a `Gender` feature, which should be limited to pronouns in English.

https://universal.grew.fr/?custom=66f0105ee75b5

It appears that most of these are borrowed or foreign words. Borrowed words do not have English gender. For the options for annotating foreign words, see https://universaldependencies.org/foreign.html

**Comment by nschneid** [comment]
@msang Will it be possible to fix this soon? I'm hoping it's a simple fix, but I want to make sure we leave enough time for any discussion before the Nov. 1 data freeze.

**Comment by msang** [comment]
I'm sorry, I've been missing a lot of notifications from GitHub. Yes, I'll get this fixed in the next couple days. Thanks!

**Comment by nschneid** [comment]
Looks like 2 more:

(in en_partut-ud-train.conllu) Line 41350 Sent en_partut-ud-1786]: [L4 Morpho feature-value-upos-not-permitted] Value Fem of feature Gender is not permitted with UPOS DET in language [en].

[(in en_partut-ud-train.conllu) Line 41353 Sent en_partut-ud-1786]: [L4 Morpho feature-value-upos-not-permitted] Value Fem of feature Gender is not permitted with UPOS DET in language [en].

**Comment by msang** [comment]
Fixed it, thanks!
